# Generated by Django 5.2 on 2025-04-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'Message'), ('system', 'System'), ('alert', 'Alert')], default='system', max_length=10),
        ),
    ]
